// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title MultiLaunchEscrow
 * @dev Central settlement "Cash Register" contract on Base network.
 * Receives USDC directly or via cross-chain bridge solvers (LI.FI / deBridge)
 * and emits LaunchPaymentReceived to trigger backend relayer executions.
 */
contract MultiLaunchEscrow is Ownable {
    IERC20 public immutable usdc;
    address public treasury;

    // The backend indexer listens for this exact event
    event LaunchPaymentReceived(
        string quoteId, 
        address indexed user, 
        uint256 amount
    );

    constructor(address _usdc, address _treasury) Ownable(msg.sender) {
        require(_usdc != address(0), "Invalid USDC address");
        require(_treasury != address(0), "Invalid treasury address");
        usdc = IERC20(_usdc);
        treasury = _treasury;
    }

    /**
     * @dev Called by the user natively on Base, OR by the LI.FI/deBridge cross-chain executor
     * @param quoteId The UUID generated by the backend Quote Engine
     * @param user The address of the user initiating the launch
     * @param amount The exact USDC amount required for the launch
     */
    function payForLaunch(string calldata quoteId, address user, uint256 amount) external {
        require(amount > 0, "Amount must be greater than zero");
        require(bytes(quoteId).length > 0, "Quote ID required");

        // Transfer the USDC from the caller (User or Bridge Executor) to Treasury
        require(usdc.transferFrom(msg.sender, treasury, amount), "USDC transfer failed");
        
        // Emit the event to trigger the backend Relayer
        emit LaunchPaymentReceived(quoteId, user, amount);
    }

    function updateTreasury(address _newTreasury) external onlyOwner {
        require(_newTreasury != address(0), "Invalid treasury address");
        treasury = _newTreasury;
    }
}
